### ISSUE TITLE
Things to do for Qt port 

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#3521]
- [x] Add decimals to input/output gain spinbuttons in all plugin UI.
- [x] Add top and bottom margins to the row containing the input/output spinbuttons and levels.
- [x] Allow the effects list to be shown and hidden like in Libadwaita (with arrow buttons to move between plugin UI).
- [x] Implement plugin bypass/enable button.
- [x] Implement the presets manager.
- [x] Implement the pipewire manager.
- [x] Implement each plugin preset class.
- [x] Implement the presets UI (local and community).
- [x] Making presets autoloading functional.
- [x] Implement the spectrum.
- [x] Implement excluded apps manager.
- [x] Add/remove app names to/from excluded apps list when `Exclude` checkbox is clicked in app info card.
- [x] Implement the shortcuts window.
- [x] Bring back all the command line options and add `--gapplication-service` for compatibility with old autostart files.
- [x] Implement command line options to get the last active input/output preset.
- [x] Add something useful to the system tray icon menu.
- [x] Implementing the test signals window.
- [x] Bring back shortcuts like the ones for fullscreen, to close the window and to quit the application.
- [x] Sort the effects list by the locale strings.
- [x] Add a configuration option that allows the microphone monitor output to be sent to the output effects pipeline input.
- [x] Remove "util" functions that are not needed anymore.
- [x] Add a new Autogain parameter that allows the output level to be forced to zero when the input level is below the silence threshold.
- [x] Fixing our symbolic [icon](https://github.com/wwmm/easyeffects/blob/master/data/com.github.wwmm.easyeffects-symbolic.svg) so it does not look as bad as it is does now when showing our tray icon. For some reason it is almost completely black. I have no idea about how to fix this. Help is needed.
- [x] Preset autoloading: show the current device routing together with the device name.
- [x] Add more modes to our test signal generator #3789,
- [ ] Complete the XDG Global Shortcuts implementation (D-Bus related stuff is already done, but we need to add the operations in the `Activated` signal callback) #3834.
- [ ] Improve how `preferred trigger` are stored for XDG Global Shortcuts (maybe in an external XML database).
- [ ] Track `preferred trigger` changes from the user for Global Shortcuts (maybe listening to [ShortcutsChanged](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.GlobalShortcuts.html#org-freedesktop-portal-globalshortcuts-shortcutschanged) D-Bus signal).
- [x] Solve the `_LIBCPP_VERSION` warning shown on the first compilation.
- [x] Add the "Input Monitoring" functionality recently added to the GTK4 code.
- [x] Add a debug mode. As things are right now Easy Effects always prints debug messages.
- [x] Make the "autostart on login" functional.
- [x] Update our desktop file. DBus activatable isn't used anymore.
- [x] Find an alternative way to handle our manual that does not involve using yelp.
- [x] Try to improve our level meters. See #3809
- [x] Implement an autosave timer for the database. Right now it saves data only when our window is closed or when quitting the app.
- [x] Add a "Reset History" button to the Pitch plugin.
- [x] Copy the current translation file for each language to the proper places in the Qt branch.
- [x] [LSP 1.2.23](https://github.com/lsp-plugins/lsp-plugins/releases/tag/1.2.23): Add audio channel pre-mixing controls for Compressor, Expander, Gate, Limiter, Multiband Compressor, and Multiband Gate.
- [x] [LSP 1.2.23](https://github.com/lsp-plugins/lsp-plugins/releases/tag/1.2.23): Bind the new `L/R Link` button in the Parametric Equalizer native window to our split channels property.
- [x] [LSP 1.2.23](https://github.com/lsp-plugins/lsp-plugins/releases/tag/1.2.23): Add `minimum-phase filter mode` for the loudness plugin.
- [x] [LSP 1.2.24](https://github.com/lsp-plugins/lsp-plugins/releases/tag/1.2.24): Add true peak limiting modes to the Limiter.
- [x] Add the `ISO226-2023 variant` to the loudness plugin.
- [x] Make sure that when an empty preset is loaded no plugin widgets remain visible in our window and the "no plugins" page is shown.
- [x] Our Github Action that updates the translation files probably needs to be updated.
- [x] The current approach used to set the OverlaySheets height is not the best (e.g., the inline message in the presets menu is partially covered by the footer).
- [x] Find a better way to select the visible plugin when an effects is removed (right now the code resets to the first plugin in the list, but maybe it's better to select the next/previous one related to the removed plugin).
- [x] Find a better way to select the visible plugin when an effects is added (right now the code resets to the first plugin in the list, but maybe it's better to select the newly added plugin).
- [x] EeSpinBoxes in Autogain, Bass Enhancer, Bass Loudness, Crossfeed, DN Remover, Echo Canceller, Exciter, Filter, Maximizer, RNNoise, Pitch end Reverberation need a maximum width to avoid excessive reduction of the left label (as we did in the Limiter in commit https://github.com/wwmm/easyeffects/commit/25d0b18f9556a8f2c6de28b252e442d3d7783ecd).
- [x] Convolver chart needs a minimum width otherwise the graph overflows the right boundary.
- [x] Deesser, Delay, Expander, Level Meters, Speech Processor and Stereo Tools cards need a minimum width (in certain cases the spinboxes values overflows their boundaries). We need to replicate what we did in the MB Compressor.
- [x] Gate cards do not switch to a 2 columns layout when the window width is reduced. But, oddly, the 2 columns layout is used when we switch from another effect (having the window in low width mode).
- [x] Limiter: add Pre-Mix controls to the preset manager.
- [x] implement a way to export presets. See #2523.
- [x] Add shortcuts to toggle Process All Inputs/Outputs and for the microphone monitoring.
- [x] Move the directories input, output, autoload and irs to the data place specified by the XDG standard. This will also require the implementation of a function that copies current files to the new location so our users do not have to manually do the migration.

**Comment by 103sbavert** [comment]
Is the GTK version going away or is this just a separately maintained port?

**Comment by wwmm** [comment]
> Is the GTK version going away or is this just a separately maintained port?

The gtk version will be replaced by the one in the qt branch.

**Comment by 103sbavert** [comment]
Is that you saying the GTK version is being killed?

**Comment by wwmm** [comment]
> Is that you saying the GTK version is being killed?

Yes. I do not have time to maintain both branches. And on a personal level I am not pleased by the direction things went on gtk's side. So even if I had the time the desire to keep coding with gtk is gone.

**Comment by Alex-Jupanu** [comment]
how can I try the QT version? I am on Fedora Kinoite 'Atomic'

**Comment by wwmm** [comment]
> how can I try the QT version? I am on Fedora Kinoite 'Atomic'

As I still did not port all plugins I did not put a guide for this anywhere. But the branch is this one https://github.com/wwmm/easyeffects/tree/eeqt. The workflow is the same of most apps based on `cmake` build tools:
```
mkdir build
cd build
cmake ..
cd src
./easyeffects
```
Assuming you have all the required dependencies installed it should work. No need to uninstall the gtk4 version because they do not share the same configuration database. But you can't have both running at the same time because one will undo the routing done by the other.

The core functionality is already in place. What is missing is porting the few plugins that were not yet. And as usual some polishing.

**Comment by Alex-Jupanu** [comment]
> The core functionality is already in place. What is missing is porting the few plugins that were not yet. And as usual some polishing.

Nice, I'm looking forward to a flatpak release when the software is fully polished!

**Comment by wwmm** [comment]
>Nice, I'm looking forward to a flatpak release when the software is fully polished!

Under normal circumstances it would be possible to test the development  branch through Flatpak. But right now the build fails because The Qt compiled in the runtime does not have `QtGraphs` enabled for some reason. @violetmage  do you know if there is way to have that? I tried my best to adapt our current flatpak scripts but maybe there is something obvious I am missing https://github.com/wwmm/easyeffects/blob/eeqt/util/flatpak/com.github.wwmm.easyeffects.Devel.json.

**Comment by violetmage** [comment]
AFAICT the only option is to compile a custom qt, unless someone makes an sdk extension or baseApp or something on flathub. There's a baseApp thing for [qtwebengine](https://github.com/flathub/io.qt.qtwebengine.BaseApp), but not much else.

**Comment by wwmm** [comment]
> AFAICT the only option is to compile a custom qt, unless someone makes an sdk extension or baseApp or something on flathub. There's a baseApp thing for [qtwebengine](https://github.com/flathub/io.qt.qtwebengine.BaseApp), but not much else.

I see. As there is still a lot of work to be done in the Qt branch I think it is not worth the effort of trying this now. Let's wait a little more for people to build Qt with QtGraphs by default. Arch is already doing that. I wonder why other maintainers have decided to disable it. It is not like it causes any conflict with QtCharts.

**Comment by ramdomPTM** [comment]
Hi all! I saw the icon problem and thought maybe I could offer some thoughts, though I am not a designer. 16px icons should have 1px line width and 2px margins, if I recall it right. I did a draft which looks like 

![Image](https://github.com/user-attachments/assets/659dafc0-945c-4331-9818-e133ac5518fa)

KDE's new design system is worth looking into. I'll paste the link here: https://www.figma.com/design/F38rWWFmFRcyolDk07xxKw/Icons

**Comment by ramdomPTM** [comment]
It seems to be related to svg masks, according to [a thread on Affinity forum](https://forum.affinity.serif.com/index.php?/topic/141104-svg-file-opening-with-blacked-out-background/) about a similar issue.

I removed all elements of the icon in Inkscape but it still showed a black square in Dolphin preview. Opening with a text editor showed a filter and 12 masks and clips from "b" to "m", which I don't know how to view or modify in Inkscape.

```xml
  <filter
     id="a"
     x="0"
     y="0"
     width="1"
     height="1">
    <feColorMatrix
       in="SourceGraphic"
       values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"
       id="feColorMatrix1" />
  </filter>
  <mask
     id="b">
    <g
       filter="url(#a)"
       id="g1">
      <rect
         width="16"
         height="16"
         fill-opacity=".55"
         id="rect1" />
    </g>
  </mask>
  ...
```

It turned out that removing these filters and masks and clips fixed the background issue.

Before:

![Image](https://github.com/user-attachments/assets/daf154b6-b77a-4184-b7e3-cc2f4646fb50)

After:

![Image](https://github.com/user-attachments/assets/7db23b76-9d7d-462c-875c-6705d1162291)

**Comment by wwmm** [comment]
@ramdomPTM I ǘe tried the new symbolic icon and the background issue is indeed fixed. Thanks! But the color still does not follow what is set in the theme. When using a light theme things seem fine:

![Image](https://github.com/user-attachments/assets/3d0fa5c8-d679-4d13-858f-526a0da9e0e3)
But when swtiching to a dark theme the icon color does not switch to white

![Image](https://github.com/user-attachments/assets/93d7c550-9077-4e81-9f38-a72ff0c24895)

. So there is something kde frameworks expects us to do in this icon that is not done yet.

**Comment by ramdomPTM** [comment]
Oh, I need to embed a stylesheet in the icon, according to the [KDE community wiki](https://community.kde.org/Guidelines_and_HOWTOs/Icon_Workflow_Tips#Embedding_stylesheets_in_SVGs). I'll open a new PR for the icon.

**Comment by wwmm** [comment]
>Oh, I need to embed a stylesheet in the icon, according to the [KDE community wiki](https://community.kde.org/Guidelines_and_HOWTOs/Icon_Workflow_Tips#Embedding_stylesheets_in_SVGs). I'll open a new PR for the icon.

This alone is not enough. I am suspecting that the icon has to be in a specific location for this to work. Now I remember that last year I tried to embed one of breeze's icons in our executable and the recoloring totally failed too. While it worked just fine when telling Qt to use the system icon.

**Comment by wwmm** [comment]
At this moment we install this icon at this location `/usr/share/icons/hicolor/symbolic/apps/com.github.wwmm.easyeffects-symbolic.svg`. Maybe it is a bad path...

**Comment by ramdomPTM** [comment]
[NeoChat](https://github.com/search?q=repo%3AKDE%2Fneochat%20tray&type=code) (a matrix client by KDE) implemented dynamic tray icon. They put the tray icon at `/usr/share/icons/hicolor/scalable/apps/org.kde.neochat.tray.svg`. Their icon can dynamically change color along with system color theme in an icon selector e.g. directory properties in Dolphin, but putting the icon I made in the same directory didn't have the same effect... Maybe there's a cache to clean somewhere, for I duplicated NeoChat's tray icon and modified it and icon selector couldn't see the changes.

**Comment by v-fox** [comment]
> [NeoChat](https://github.com/search?q=repo%3AKDE%2Fneochat%20tray&type=code) (a matrix client by KDE) implemented dynamic tray icon. They put the tray icon at `/usr/share/icons/hicolor/scalable/apps/org.kde.neochat.tray.svg`. Their icon can dynamically change color along with system color theme in an icon selector e.g. directory properties in Dolphin, but putting the icon I made in the same directory didn't have the same effect... Maybe there's a cache to clean somewhere, for I duplicated NeoChat's tray icon and modified it and icon selector couldn't see the changes.

Oh, there is definitely some cache. I would expect it to refresh automatically but bloated things never work conveniently.
In fact, there are 2-3 caches: common xdg icon cache and kde/plasma's `kcache` and `ksycoca`(maybe this one is not for icons [anymore]?).
So, might want to try deleting things like:
```
~/.cache/icon-cache.kcache
~/.cache/plasma_theme_internal-system-colors.kcache
~/.cache/plasma_theme_default.kcache
~/.cache/ksycoca*
```
xdg cache seems to be still sitting in `/usr/share/icons/<theme-name>/icon-theme.cache` (maybe user's installs/changes duplicate it in `~/.local/share/icons`?). They still haven't bothered to move it into `/var/cache`.

Which is why all distros still have to manually call forced icon cache regen on every installation change, including every `hicolor` theme-related change…

**Comment by wwmm** [comment]
> So, might want to try deleting things like:
> 
> ```
> ~/.cache/icon-cache.kcache
> ~/.cache/plasma_theme_internal-system-colors.kcache
> ~/.cache/plasma_theme_default.kcache
> ~/.cache/ksycoca*
> ```

I tried and the situation is the same. But I did not try to move the icon to a different path.

**Comment by wwmm** [comment]
>but putting the icon I made in the same directory didn't have the same effect... 

Same thing here. It seems we will have to ask KDE developers directly about this. Just in case someone is able to see something we couldn't this is the content of neochat icon

```
<svg width="22" height="22" viewBox="0 0 22 22" fill="none" xmlns="http://www.w3.org/2000/svg">
<style type="text/css" id="current-color-scheme">.ColorScheme-Text{color:#232629}</style>
<path class="ColorScheme-Text" fill-rule="evenodd" clip-rule="evenodd" d="M3 3H19V14H8.68787L4 18.1019V14H3V3ZM4 13H5V15.8981L8.31213 13H18V4H4V13Z" fill="currentColor"/>
<path class="ColorScheme-Text" fill-rule="evenodd" clip-rule="evenodd" d="M17 15.2929L14.8536 13.1465L14.1465 13.8536L18 17.7071V13.5H17V15.2929Z" fill="currentColor"/>
<path class="ColorScheme-Text" d="M5 6H15V7H5V6Z" fill="currentColor"/>
<path class="ColorScheme-Text" d="M5 8H13V9H5V8Z" fill="currentColor"/>
<path class="ColorScheme-Text" d="M5 10H11V11H5V10Z" fill="currentColor"/>
</svg>
```
And this is how our symbolic icon is
```
<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
    <g class="ColorScheme-Text" fill="currentColor">
        <rect id="rect1" x="7.5" y="2" width="1" height="12" ry=".5"/>
        <rect id="rect2" x="12" y="4" width="1" height="8" ry=".5"/>
        <rect id="rect3" x="3" y="4" width="1" height="8" ry=".5"/>
        <circle id="circle1" cx="8" cy="5" r="1.5"/>
        <circle id="circle2" cx="12.5" cy="9" r="1.5"/>
        <circle id="circle3" cx="3.5" cy="7.5" r="1.5"/>
    </g>
    <style type="text/css" id="current-color-scheme">
        .ColorScheme-Text {
            color: #232629;
        }
    </style>
</svg>
```

**Comment by Digitalone1** [comment]
Maybe now I remember why we didn't use `recursive_directory_iterator`.

It collects everything in the folder and its subfolders recursively, but we need only the first level.

I proposed it to make the directory/file structure more simple for community presets: https://github.com/wwmm/easyeffects/blob/master/COMMUNITY_PRESETS_GUIDELINES.md?plain=1#L224-L227

**Comment by wwmm** [comment]
> Maybe now I remember why we didn't use `recursive_directory_iterator`.
> 
> It collects everything in the folder and its subfolders recursively, but we need only the first level.
> 
> I proposed it to make the directory/file structure more simple for community presets: https://github.com/wwmm/easyeffects/blob/master/COMMUNITY_PRESETS_GUIDELINES.md?plain=1#L224-L227

Oh... I forgot about it. Honestly in this case we should just silence the clang-tidy and move on to the other things that still need to be done.

**Comment by wwmm** [comment]
Current state of our tray menu

<img width="204" height="372" alt="Image" src="https://github.com/user-attachments/assets/9cb3faef-772a-4e6d-9f63-2a556082912d" />

Qml tray menus have way more limitations than I expected. Initially I intended to have submenus for each pipeline. And a list of presets on them. But it does not seem possible... So instead we will show the 4 most used presets. They can be activated from there :-). I think that this is enough for now.

**Comment by wwmm** [comment]
Our qt branch has become good enough to replace our master branch. I did that now. Arch Linux users can use the `PKGBUILD_AUR` available in our repository until the AUR package is properly updated by people more capable in this regard.

Flatpak users can get one of the development packages built by our github actions https://github.com/wwmm/easyeffects/actions.

The application still needs more polishing before an official release. As usual the more people helping with tests the better!

**Comment by wwmm** [comment]
>As usual the more people helping with tests the better!

Specially the ones that do not run KDE or GNOME. I use KDE and @Digitalone1 GNOME. So we have an idea about what is good or not in these desktops. About the others I have almost no information at all. And as we use Arch Linux there is an obvious bias to this distribution. Feedback from other distributions users are also welcome.

**Comment by wwmm** [comment]
As it happened in past major changes a legacy branch was created for the old gtk4 code https://github.com/wwmm/easyeffects/tree/gtk4-legacy. Do not expect normal updates there. As in the other cases if something gets severely broken we might take a look and try to fix. But we barely have time to maintain one branch.

**Comment by ramdomPTM** [comment]
Congrats on merging the Qt branch! Been away for a while, but the recent progress looks very promising. Very exited for the next major release. And seems that the tray icon is now working (d14dabf). I wonder what's the trick? :wink:

**Comment by wwmm** [comment]
> And seems that the tray icon is now working ([d14dabf](https://github.com/wwmm/easyeffects/commit/d14dabfdcd7fa5910533e997e9199819edae206c)). I wonder what's the trick? 😉

I was about to give up when I found the solution totally by chance 😄 . In all places where a color is set we have to do `color:currentColor` instead of inserting the color code. The only place where a color is set `.ColorScheme-Text { color: #fcfcfc; }`. We had the color scheme set before. But some parts of the drawing had their colors hardcoded with the color code instead of currentColor. And setting `style="color:currentColor;fill:currentColor;fill-opacity:1"` to the group probably helped too.

**Comment by rcv11x** [comment]
Hello, impressive work everyone who has contributed to the QT port. I've been following the progress on GitHub along with the commits. I have a question: when will the new version of easyeffetcs be available in the repositories? In my case, I'm on Arch, and I'm really looking forward to trying it out. Best regards, and keep up the good work!

**Comment by wwmm** [comment]
> Hello, impressive work everyone who has contributed to the QT port. I've been following the progress on GitHub along with the commits. I have a question: when will the new version of easyeffetcs be available in the repositories? In my case, I'm on Arch, and I'm really looking forward to trying it out. Best regards, and keep up the good work!

Thanks! :-). There isn't a date yet. Although the application is 100% functional after such a radical change it is necessary to spend some time polishing the rough edges. But as you are also on Arch Linux user it is quite easy to test the Qt port. You can use our [pkgbuild](https://github.com/wwmm/easyeffects/blob/master/PKGBUILD_AUR) until AUR's easyeffects-git package is updated to our current master branch.

**Comment by wwmm** [comment]
> Along with shortcuts for processing input and output and bypassing, can we also get one for input monitoring?

It is just a matter of thinking about a good keyboard key combination. Maybe we could use `Ctrl+I` for the shortcut that needs our window to be the one in focus and `Ctrl+Alt+I` for the global shortcut.

**Comment by wwmm** [comment]
@vchernin Our echo canceller now uses webrtc (version 2) instead of speexdsp. I tried to use what chatgpt generated to fix the Flatpak build but as our CI output shows it did not go well 😄 .

**Comment by wwmm** [comment]
Just in case other Arch Linux users are wondering why Calf Studio Plugins native window is not being shown by EasyEffects anymore the reason is that Arch's package stopped enabling its native window https://gitlab.archlinux.org/archlinux/packaging/packages/calf/-/issues/3. As Arch will drop gtk2 from its repositories Calf's package can't have its native window anymore... For a moment I thought it was a problem on our side and I was already trying to debug the issue... Well... As users from other distributions may still have the native window there I think we should still show the native window button for Calf plugins.

**Comment by v-fox** [comment]
> As Arch will drop gtk2 from its repositories Calf's package can't have its native window anymore.

How could have Arch do this to Linux community? Any sane person known that GTK-2 is the only good GTK.

I'm on Gentoo but I've considered Arch as one of the few good ones left, not counting some other dumbness. Even on Gentoo, only GTK-2 works properly for me. For some reason if X11 is not forced via `GDK_BACKEND=x11` for GTK 3 and 4, its performance is atrocious (with no errors to debug, of course) under KDE in Wayland-mode, as if everything is rendered on single-core CPU from 1995. I even had to migrate from "fancy long-awaited" Gimp-3 to Krita from git-snapshots because of it.
So only Qt6 and GTK2 apps work properly without crutches. It's absurdly comedic.

Which is why I'm glad for this migration from GTK-4 to Qt-6, despite Qt being unwieldy fat, prone to breaking system from not properly versioning its ABI on every major update and burying whole bunch of my favourite apps due to frivolous and deep breakage of API compatibility (such as KDE-3.5, the best DE ever).

**Comment by Digitalone1** [comment]
> How could have Arch do this to Linux community? Any sane person known that GTK-2 is the only good GTK.

Arch supports various DE, not only Plasma. And old software is not supported, like python2 packages.

**Comment by v-fox** [comment]
> > How could have Arch do this to Linux community? Any sane person known that GTK-2 is the only good GTK.
> 
> Arch supports various DE, not only Plasma. And old software is not supported, like python2 packages.

And how "supporting other DEs" relevant to nuking GTK-2 which is a dependency for actually good apps and the best GTK version?

**Comment by Digitalone1** [comment]
> And how "supporting other DEs" relevant to nuking GTK-2 which is a dependency for actually good apps and the best GTK version?

The opinion that GTK2 is the best GTK is not relevant since most recent apps do not use it anymore. It's old software and Arch do not support it forever. The problem is that Calf won't upgrade to GTK3: https://github.com/calf-studio-gear/calf/issues/328

Anyway, gtk2 has been moved on AUR: https://aur.archlinux.org/packages/gtk2

**Comment by v-fox** [comment]
> The opinion that GTK2 is the best GTK is not relevant since most recent apps do not use it anymore. It's old software and Arch do not support it forever. The problem is that Calf won't upgrade to GTK3: https://github.com/calf-studio-gear/calf/issues/328

No, the problem is that Calf won't upgrade to Qt or FLTK. Because it's de facto dead.
But at least it's not polluted by post-GTK2, Rust and other broken-by-design fads.

But let's drop pretences: breaking deliberately, what is not broken, is delusion or malice. I would expect something like this from likes of Red Hat and Debian/Ubuntu but not Arch.
I was actually choosing between Gentoo and Arch for migration from rotted openSUSE recently, chose to avoid Arch due to bad vibes. This is a confirmation for them.

**Comment by wwmm** [comment]
For a long time we have been saving presets, impulse response, rnnoise and autoload profile files in our configuration folder. What is not what XDG standard suggests to be done. Now is the time to change that. Our master branch now saves these files inside `~/.local/share/easyeffects` and keeps only our database files inside `~/.config/easyeffects`. EasyEffects will copy the current files to the new location and move the old directories to the users trash. This way if something horrible happens the user will be able to get the files back.

@vchernin and @violetmage let me know if something unusual happens in the Flatpak package. I used `QFile::moveToTrash` to move files to the user trash but I have no idea if this will work in the Flatpak package.

**Comment by Digitalone1** [comment]
@wwmm Please, report this change into release notes.

**Comment by wwmm** [comment]
> [@wwmm](https://github.com/wwmm) Please, report this change into release notes.

Done. 

Our long Qt port to do list is almost over. The only points remaining are about the global shortcuts. But at least here on KDE it does not feel like we need to do anything more about them. @Digitalone1 what is the current state on GNOME? Do we need the points in the to do list? The one about using the database does not feel necessary anymore. For now the `ee_global_shortcuts_array` seems enough. And handling description translations there probably will be easier. 

I think we progressed enough to finally make this release. Unless something major happens I intend to do it Friday morning.

**Comment by wwmm** [comment]
> I think we progressed enough to finally make this release. Unless something major happens I intend to do it Friday morning.

This would give us time for some minor polishing. And to write the changelog. The challenge will be to remember the changes that deserve to be mentioned there after so long 😄 .

**Comment by Digitalone1** [comment]
> [@Digitalone1](https://github.com/Digitalone1) what is the current state on GNOME? Do we need the points in the to do list? The one about using the database does not feel necessary anymore. For now the `ee_global_shortcuts_array` seems enough. And handling description translations there probably will be easier.

When I have time I will test them more in depth and let you know.

**Comment by vchernin** [comment]
> For a long time we have been saving presets, impulse response, rnnoise and autoload profile files in our configuration folder. What is not what XDG standard suggests to be done. Now is the time to change that. Our master branch now saves these files inside `~/.local/share/easyeffects` and keeps only our database files inside `~/.config/easyeffects`. EasyEffects will copy the current files to the new location and move the old directories to the users trash. This way if something horrible happens the user will be able to get the files back.
> 
> [@vchernin](https://github.com/vchernin) and [@violetmage](https://github.com/violetmage) let me know if something unusual happens in the Flatpak package. I used `QFile::moveToTrash` to move files to the user trash but I have no idea if this will work in the Flatpak package.

Works fine for me. Fundementally this migration should be safe since easyeffects has likely always respected the `XDG_CONFIG_DIR` and `XDG_DATA_DIR` variables. They should point to the same locations for both GTK and QT on one system.

```bash
easyeffects: presets_directory_manager.cpp:140	Old /var/home/vchernin/.var/app/com.github.wwmm.easyeffects.Devel/config/easyeffects/input directory detected. Migrating its files to /var/home/vchernin/.var/app/com.github.wwmm.easyeffects.Devel/data/easyeffects/input
easyeffects: presets_directory_manager.cpp:146	Moved /var/home/vchernin/.var/app/com.github.wwmm.easyeffects.Devel/data/easyeffects/input to the trash folder
```


See https://docs.flatpak.org/en/latest/conventions.html#xdg-base-directories

**Comment by Digitalone1** [comment]
> [@Digitalone1](https://github.com/Digitalone1) what is the current state on GNOME? Do we need the points in the to do list? The one about using the database does not feel necessary anymore. For now the `ee_global_shortcuts_array` seems enough. And handling description translations there probably will be easier.

I changed the shortcut for the bypass and it works, but I don't know if it's retained across reboots (maybe I will test it later).

<p><img width="597" height="381" alt="Image" src="https://github.com/user-attachments/assets/aff02845-8fab-47b7-8cdd-f0e4686eb9cc" /></p>

It's interesting to note that I can't restore the shortcut to the default value, so if I change it and Easy Effects will register it later, I suppose it will default back to CTRL+ALT+E. Maybe the callback to track the changes is made to give the opportunity to register what the user have set.

**Comment by wwmm** [comment]
>so if I change it and Easy Effects will register it later, I suppose it will default back to CTRL+ALT+E

Hum... As kde is handling this we do not need to register anything. What happens is that kde redirects the new shortcut selected by the user on its own. From easyeffects  point of view it is like the default shortcut was used. And considering what you described so far gnome is also doing some kind of redirection on its own. Otherwise the new shortcut would not have worked. 

What is concerning is gnome not being clear about how to restore the default shortcut. Even if we try to register the custom user shortcut and handling it ourselves this would be pointless if gnome sends us the default because of the redirection.

In any case I think we can move on and do the release Friday morning . There is still too much difference from one desktop to another for global shortcuts to be a blocker on our side. And despite the differences between desktops global shortcuts are useful enough as things are right now.

**Comment by wwmm** [comment]
Ready or not, here we go. EasyEffects 8.0.0 released! This journey has been a lot longer than I initially expected. More than one year of hard work. But I think it was worth it. Quite a lot of our almost 50 thousand lines of code has been touched one way or another. Now it is time to see how our new codebase will interact with the sea of Linux distributions.

More details about the changes in our [changelog](https://github.com/wwmm/easyeffects/blob/master/CHANGELOG.md). But I doubt I remembered everything that has been done while writing it 😄 .

Time to close this issue.

**Comment by ramdomPTM** [comment]
Great news, and congratulations! I've already submitted a request to openSUSE at https://build.opensuse.org/requests/1316677, but I'm not familiar with cmake packaging using rpm, so if anyone is also packaging for openSUSE or Fedora, or has experiences at cmake packaging, please feel free to have a look at the [spec file](https://build.opensuse.org/projects/home:ramdomPTM:branches:multimedia:apps/packages/easyeffects/files/easyeffects.spec?expand=1) and point out anything that is not best practice. Thanks!

**Comment by craftfever** [comment]
Congratulations, it's exciting actually, from all its interface and engine rewriting and fixing huge amount of bugs in detail. I remembering screenshots of early stages of development and that is very detailed work to fix this small bugs that affects app working very much. Thank you for amazing work, this release is great.

**Comment by win8linux** [comment]
Hey there, this app has just been featured in [This Week in KDE Apps](https://blogs.kde.org/2025/11/10/this-week-in-kde-apps/#easy-effects---audio-effects-for-pipewire-applications)!

Congratulations to Easy Effects on a successful transition and the contributors are very much welcome in the KDE Community, especially in the Kirigami (`#kirigami:kde.org`) and Streamlined App Dev Experience (`#kde-apps-initiative:kde.org`) Matrix rooms.

**Comment by dphaldes** [comment]
> Congratulations to Easy Effects on a successful transition and the contributors are very much welcome in the KDE Community, especially in the Kirigami (#kirigami:kde.org) and Streamlined App Dev Experience (#kde-apps-initiative:kde.org) Matrix rooms.

To second this, EasyEffects uses lots of unique components and different design ideas compared to other Kirigami Apps and the KDE HIG. I would love to have a discussion about improving the app while also improving Kirigami and refining the HIG. Feel free to reach out :)

**Comment by wwmm** [comment]
> To second this, EasyEffects uses lots of unique components and different design ideas compared to other Kirigami Apps and the KDE HIG. I would love to have a discussion about improving the app while also improving Kirigami and refining the HIG. Feel free to reach out :)

I think I never used these kind of channels but I will try to do that. For example as I explained at https://github.com/wwmm/easyeffects/pull/4333 I have seen some unexpected behavior when using `Kirigami.AbstractApplicationHeader` that has been hard to understand on my own. How do we use these matrix rooms? Web Browser? Or through an app like KDE neochat?

And feedback about the user interface is definitely welcome. I think I said this somewhere in the past but my academic background is physics and not software or graphical interface design 😄 

I have already noticed I am not following HIG recommendations like only using overlaysheets for long read-only information. But when I tried a dialog in their place the size of the header and overall appearance felt strange... So some input about the HIG would be good.

**Comment by dphaldes** [comment]
Yes, you can use any of the Matrix clients (web based one like Element or Cinny) or a desktop app (Neochat and Fractal). It's basically an open chat platform (think discord but federated). KDE's matrix server special channels for discussions about Kirigami, general KDE libraries (if you are using any) and Visual Design. Just create an account and join any of the channels 
from this list https://community.kde.org/Matrix (just click on any of the links and it will prompt you to create an account and/or launch your client)

**Comment by Digitalone1** [comment]
@wwmm Please unpin this one and pin #4433.
